build: off

environment:
  nodejs_version: "8.11.1"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g yarn
  - yarn
  - yarn tsc

before_test:
  - node --version
  - npm --version

test_script:
  - yarn test:ci
